# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Momentum Team 13 Course Site
team_name: "Team 13"
tagline: A Jekyll template for course websites
description: Based on Kevin Lin's Just The Class jekyll theme
baseurl: '/staging' # the subpath of your site, e.g. /blog
url: 'https://momentum-team-13.github.io'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", ".jekyll-cache", ".sass-cache"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: mmntm
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  "GitHub":
    - "//github.com/momentum-team-13"
footer_content: "&copy;2022 Momentum"
logo: "/assets/images/momentum__mark-digital-royal.png"
zoom_link: 'https://us02web.zoom.us/j/88017099254?pwd=S0dXVDlNaE1wWU1uTE5mVFFDa0xoZz09'

# Collections for website data
# just_the_docs:
collections:
  schedules:
    name: schedules
    nav_exclude: false
  general_posts:
    name: general_posts
    path: 'posts/'
    output: true
    nav_exclude: false
  modules:
    name: modules
    output: true
    nav_exclude: true


# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: general_posts
      type: pages
    values:
      layout: general_post

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-remote-theme

sass_dir: /_sass
